services:
  db:
    image: mysql:8.3
    container_name: "wedding-db"
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: wedding
      TZ: Asia/Seoul
    volumes:
      - ./db/mysql/data:/var/lib/mysql
      - ./db/mysql/config:/etc/mysql/conf.d
      - ./db/mysql/init:/docker-entrypoint-initdb.d
    networks:
      - wedding
    restart: always

  app:
    image: eunhomoon/wedding:latest
    container_name: "wedding"
    ports:
      - "9080:8080"
    environment:
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      JWT_ISSUER: ${JWT_ISSUER}
      JWT_SECRET_KEY: ${JWT_SECRET_KEY}
    networks:
      - wedding
      - services
    restart: always

networks:
  wedding:
    driver: bridge
  services:
    external: true