spring:
  profiles:
    default: prod

  datasource:
    url: 'jdbc:h2:mem:wedding-much'
    username: 'sa'
    password: ''

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
    show-sql: true
  h2:
    console:
      enabled: true
      path: '/h2-console'

---
spring:
  config:
    activate:
      on-profile: test

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
    show-sql: true
