spring:
  profiles:
    default: dev

  jpa:
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100
    show-sql: true

---
spring:
  config:
    activate:
      on-profile: prod

  jpa:
    hibernate:
      ddl-auto: none

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver

---
spring:
  config:
    activate:
      on-profile: dev

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/wedding
    url: jdbc:mysql://wedding-db:3306/wedding
    username: root
    password: 1234

  jpa:
    hibernate:
      ddl-auto: update

---
spring:
  config:
    activate:
      on-profile: test

  datasource:
    url: 'jdbc:h2:mem:wedding-much'
    username: 'sa'
    password: ''

  h2:
    console:
      enabled: true
      path: '/h2-console'

  jpa:
    hibernate:
      ddl-auto: create
